### PR TITLE
Add APIs to support synchronous context

### PR DESCRIPTION
**Pull request by Steve-Mcl**
## Description

* adds a route: GET `/v1/context/:projectId/cache` for access to all data (for loading cache from DB -> plugin)
    * adds driver function `getAll` to service the response to GET cache 
* adds a route: POST `/v1/context/:projectId/cache/:scope` to support writing of cache data to DB
    * updates driver function `set` to support the to POST route `set` 
* updates `parseScope` to be bi-directional (required for returning Node-RED style scope IDs)
   * e.g. Node-RED node context is `<nodeId>:<flowId>`, DB scope is `<flowId>.nodes.<nodeId>`
   * e.g. Node-RED flow context is `<flowId>`, DB scope is `<flowId>.flow`
* Adds pagination support for loading cache data
   *  Default page size set to 30 scopes (if omitted in the request)
* Adds unit tests for loading and writing cached data
* Remove Context Memory driver
* Remove Context Redis driver
* Update tests for removal of unused context drivers

## Related Issue(s)

https://github.com/flowforge/flowforge-nr-persistent-context/issues/17

## TODO
- [x] Either update redis driver to support cache, disable redis driver or remove redis driver altogether
    - removed context redis driver - can be retrieved from git history is required in the future
- [x] Either update memory driver to support cache, disable memory driver or remove memory driver altogether
    - removed context memory driver - can be retrieved from git history is required in the future
- [ ] Once merged into main
    - [ ] re-run tests https://github.com/flowforge/flowforge-nr-persistent-context/pull/18
    - [ ] switch https://github.com/flowforge/flowforge-nr-persistent-context/pull/18 from draft to release and assign reviewer

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by knolleary** [comment]
Comments on the TODOs before I review code:

 - Redis - should be removed IMHO. We don't use it. It is in the git history if we need to go back to it. Keeping it in the code base is a maintenance overhead to keep it in sync with items like this.
 - Memory - how/when is this used? Is it a convenience for testing with or do we expect it to be actually used?

**Comment by Steve-Mcl** [comment]
> Memory - how/when is this used? Is it a convenience for testing with or do we expect it to be actually used?

It was a convenience for testing (to reduce need to setup a redis) however since we added sequelize we also added tets for sequelize+sqlite & sequelize+postgres

> Redis - should be removed IMHO. We don't use it. It is in the git history if we need to go back to it
Agree and happy to remove.

**Comment by Steve-Mcl** [comment]
@knolleary - TODO items implemented (1st comment update to reflect)

**Comment by knolleary** [comment]
If we paginate on scopes, then it is still possible (and likely) to have everything returned in a single request because it is all stored in one scope (ie one flow). That said, I can't immediately see a reasonable way to paginate otherwise.

**Comment by Steve-Mcl** [comment]
> That said, I can't immediately see a reasonable way to paginate otherwise.

I came to the same conclusion. 

I had to center the implementation around getting pagination in place, in readiness for future possibilities.

**Review by knolleary — APPROVED** [review]

**Pull request merged**
